local I = require('openmw.interfaces')

I.Settings.registerPage({
   key = 'CharacterAppearanceFrameworkPage',
   name = 'Character Appearance Framework',
   l10n = 'CharacterAppearanceFrameworkPage',
   description = 'Character Appearance Framework is a mod that allows VFX to be dynamically applied to and removed from NPCs and creatures, including the player character, based on configuration files installed by the user.',
})